<!-- As a link -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #272727;">
    <div class="container">
        <a class="navbar-brand" href="./home">Entepool</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <?php
                include_once 'nav_link.inc';
                ?>
            </ul>
        </div>
    </div>
</nav>